# Generated by Django 5.2.15 on 2026-06-28 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espn_id', models.CharField(max_length=80, unique=True)),
                ('abbreviation', models.CharField(blank=True, max_length=20)),
                ('display_name', models.CharField(max_length=120)),
                ('logo_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_key', models.CharField(max_length=40, unique=True)),
                ('source_event_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('round_key', models.CharField(max_length=20)),
                ('round_name', models.CharField(max_length=60)),
                ('points', models.PositiveIntegerField()),
                ('position', models.PositiveIntegerField()),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=40)),
                ('is_complete', models.BooleanField(default=False)),
                ('source', models.CharField(default='fallback', max_length=20)),
                ('score_one', models.IntegerField(blank=True, null=True)),
                ('score_two', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_one', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_one_matches', to='brackets.team')),
                ('team_two', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_two_matches', to='brackets.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='brackets.team')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_key', models.CharField(max_length=40)),
                ('team_espn_id', models.CharField(max_length=80)),
                ('team_abbreviation', models.CharField(blank=True, max_length=20)),
                ('team_display_name', models.CharField(max_length=120)),
                ('team_logo_url', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='brackets.bracket')),
            ],
            options={
                'ordering': ['slot_key'],
                'constraints': [models.UniqueConstraint(fields=('bracket', 'slot_key'), name='unique_pick_per_slot')],
            },
        ),
    ]
