# Generated by Django 5.2.15 on 2026-06-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='match',
            name='previous_slot_one',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='match',
            name='previous_slot_two',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
