# Generated by Django 5.2.15 on 2026-06-29 00:52

import django.db.models.deletion
from django.db import migrations, models
import secrets


def backfill_edit_tokens(apps, schema_editor):
    Bracket = apps.get_model("brackets", "Bracket")
    for bracket in Bracket.objects.all():
        bracket.edit_token = secrets.token_urlsafe(24)
        bracket.save(update_fields=["edit_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0002_match_match_number_match_previous_slot_one_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('token', models.SlugField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bracket',
            name='edit_token',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.RunPython(backfill_edit_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bracket',
            name='edit_token',
            field=models.CharField(blank=True, max_length=80, unique=True),
        ),
        migrations.AddField(
            model_name='bracket',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InviteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_key', models.CharField(max_length=120)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bracket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite_submission', to='brackets.bracket')),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='brackets.invite')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('invite', 'device_key'), name='unique_invite_submission_per_device')],
            },
        ),
    ]
