# Generated by Django 5.2.15 on 2026-06-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brackets', '0003_invite_bracket_edit_token_bracket_is_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='bracket_title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
