# Generated by Codex on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brackets", "0005_sitesettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="venue_city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="match",
            name="venue_name",
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
